datasetname : 'visionin_samsung_task3'

root_dir: 'D:/visionin/workspace/datasets/samsung_house/Samsung/aircon/segmentation'
train_dir: 'D:/visionin/workspace/datasets/samsung_house/Samsung/aircon/segmentation/train'
val_dir: 'D:/visionin/workspace/datasets/samsung_house/Samsung/aircon/segmentation/val'

mean : [0.0, 0.0, 0.0]
std : [1.0, 1.0, 1.0]

num_cls : 3
cls : {'rotor': 1, 'stator': 2, 'penmark': 3}

#cls_w : [0.3, 0.3, 0.2, 0.2]
cls_w : None

color_dic : [[0,   0,   0],
            [241,  90, 255],
            [158,  7,  66],
            [64, 243,   0],
            [232,  46,  62],
            [59,  30, 247],
            [67, 250, 250]]